### ISSUE TITLE
Feature request: write output file to same directory as input file

### ISSUE THREAD

**Issue by tremby** [mjwoodcock/riscosarc#1]
I'm trying to decompress a bunch of files at once, which may be at any depth in the filesystem. To have the uncompressed versions alongside the compressed, at the moment I'm using this:

    find . -name "*,d96" -exec bash -c 'echo riscosarc -x -F -d"$(dirname "{}")" "{}"' \;

It's unpleasant to say the least. I wonder if there could be an option which says to use the same directory for output as the input file.

**Comment by mjwoodcock** [comment]
This is easy enough for archives that don't contain a directory structure.

How would I handle archives with a directory structure?  Start the directory structure from the directory containing the archive file?  I could do that by default and add an option (if one doesn't exist) to remove the paths (like unzip's "-j" argument).

**Comment by tremby** [comment]
Ah, I haven't come across any like that yet, only with single-file CFS-compressed files.

But yes, I think I would expect with this "extract to same directory" option for an archive with intrinsic directory structure to have its root in the directory the archive is in. So you might get files in the archive's root extracting to that same directory the archive is in, plus new subdirectories being made. Maybe there should be some warning/protection to do with overwriting files...

I wonder what `unzip -j` does if there are multiple files in the archive in different subdirectories but with the same name. I also wonder what behaviour it has when it would overwrite a file which was *not* in the archive but had the same name as an archived file. Same questions apply to `tar x`.

**Comment by mjwoodcock** [comment]
OK, thanks makes sense.

This should be fairly simple to implement, so I should get that done soon.

**Comment by mjwoodcock** [comment]
I have changed the "-d" argument slightly.  If you use "-d-" then files will be extracted to the directory containing the archive file.

Let me know if you are happy with the change.

**Comment by tremby** [comment]
Seems to work perfectly. Thanks.

I thought at one point I had the same behaviour as `-d-` when *not* giving `-d` at all, but now I can't reproduce that. Not sure if I was imagining things.

**Comment by mjwoodcock** [comment]
Thanks for the feedback.
