### ISSUE TITLE
Feature request: option to replace original

### ISSUE THREAD

**Issue by tremby** [mjwoodcock/riscosarc#3]
I think it'd be valuable to have an option for the original file to be removed once the decompression has completed successfully. This would make it work rather like `gunzip`.

With this (and the other features I requested) it'd be much simpler to scan a whole directory tree for `*,d96` files and replace them all with their decompressed versions.

**Comment by mjwoodcock** [comment]
Yes, I can do this.  I will make the option difficult to type by accident.  Something like "--remove-archive".

**Comment by mjwoodcock** [comment]
I have pushed the change to master.  Use the "--delete-archive" argument when extracting a file to remove the original archive.

Let me know if you are happy with the change.

**Comment by tremby** [comment]
This doesn't seem to be working for me.

```
$ riscosarc -x --delete-archive \!DocData,d96
Exception in thread "main" java.lang.AbstractMethodError: Receiver class riscos.archive.container.CFSFile does not define or inherit an implementation of the resolved method 'abstract void close()' of abstract class riscos.archive.container.ArchiveFile.
        at riscosarc.main(riscosarc.java:237)
```

**Comment by mjwoodcock** [comment]
OK, I need a better build system.

You need to do "javac riscos/archive/container/*.java" to build all the correct bits.

Let me know if that fixes it for you.

**Comment by tremby** [comment]
Ah I'd only run `javac riscosarc.java` since this is what it says in the readme! I haven't done much Java.

This has fixed it. Looks to work well. It'd be worth adding that to the instructions in the readme!

**Comment by mjwoodcock** [comment]
Yes, I should do that.  I should invest in a proper build system as well.

Thanks for the feedback.
