### ISSUE TITLE
File in same directory as archive can be deleted when -d is used

### ISSUE THREAD

**Issue by tremby** [mjwoodcock/riscosarc#4]
As discovered in #2:

If I write

    echo "important data" >some-file

and then

    riscosarc -x -dsomewhere-else some-file,d96

I would think that some-file in this directory is safe since any output will be written to somewhere-else. But in fact if some-file will be overwritten and then deleted!

**Comment by mjwoodcock** [comment]
I have pushed a fix to master.

If you are happy it works, I will close this issue.

**Comment by tremby** [comment]
This no longer happens.

**Comment by mjwoodcock** [comment]
Thank you.
